spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chamongdb.cxwpt4cf2wfk.ap-northeast-2.rds.amazonaws.com:3306/chamongdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password : 79647964
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 177455669845-2r2hiar8aoibtknbo7546ii7cav76hk0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        orm:
          jpa: DEBUG
#      apache:
#        coyote:
#          http11: debug


server:
  servlet:
    encoding:
      force-response: true

jwt.key: park1234123412341234123412341234

jwt:
  access-token-expiration-millisecond: 3600000
  refresh-token-expiration-millisecond: 14400000

admin:
  email: admin@gmail.com



