spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    password: wls5177

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 177455669845-2r2hiar8aoibtknbo7546ii7cav76hk0.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true

jwt.key: park1234123412341234123412341234
jwt:
  access-token-expiration-millisecond: 3600000
  refresh-token-expiration-millisecond: 14400000
admin:
  email: admin@gmail.com
