spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://chamong-mysql.cita1h8oazuc.ap-northeast-2.rds.amazonaws.com:3306/chamongdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 79647964
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
      springframework:
        orm:
          jpa: DEBUG

  redis:
    host: localhost
    port: 6379
    password: wls5177


logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG

server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt.key: park1234123412341234123412341234
jwt:
  access-token-expiration-millisecond: 3600000
  refresh-token-expiration-millisecond: 14400000
admin:
  email: admin@gmail.com

